21-rails-review/config/routes.rb
Rails.application.routes.draw do
  resources :planets
  resources :scientists
  resources :missions, only: [:new, :create]

  get "/about", to: "application#about"
  get "/delete_scientist/:id", to: "scientists#destroy", as: "delete_scientist"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

21-rails-review/app/models/mission.rb
class Mission < ApplicationRecord
    belongs_to :planet
    belongs_to :scientist
end

21-rails-review/app/models/planet.rb
class Planet < ApplicationRecord
    has_many :missions
    has_many :scientists, through: :missions

    # def missions
    #     Mission.all.select do |mission|
    #         mission.planet_id == self.id 
    #     end
    # end

    # def scientists
    #     self.missions.map do |mission|
    #         mission.scientist 
    #     end
    # end
end

21-rails-review/app/models/scientist.rb
class Scientist < ApplicationRecord
    has_many :missions
    has_many(:planets, {through: :missions})

    validates :name, presence: true, uniqueness: true
    validates :field_of_study, presence: true

    def self.abc_order
        return Scientist.order(:name)
    end
end

21-rails-review/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def about
        @num_scientists = Scientist.count 
        @num_planets = Planet.count
        render :about
    end 
end

21-rails-review/app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def new
    @mission = Mission.new
  end

  def create 
    byebug
  end
end

21-rails-review/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  before_action :set_planet, only: [:show, :edit, :update, :destroy]

  # GET /planets
  # GET /planets.json
  def index
    @planets = Planet.all
  end

  # GET /planets/1
  # GET /planets/1.json
  def show
  end

  # GET /planets/new
  def new
    @planet = Planet.new
  end

  # GET /planets/1/edit
  def edit
  end

  # POST /planets
  # POST /planets.json
  def create
    @planet = Planet.new(planet_params)

    respond_to do |format|
      if @planet.save
        format.html { redirect_to @planet, notice: 'Planet was successfully created.' }
        format.json { render :show, status: :created, location: @planet }
      else
        format.html { render :new }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planets/1
  # PATCH/PUT /planets/1.json
  def update
    respond_to do |format|
      if @planet.update(planet_params)
        format.html { redirect_to @planet, notice: 'Planet was successfully updated.' }
        format.json { render :show, status: :ok, location: @planet }
      else
        format.html { render :edit }
        format.json { render json: @planet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planets/1
  # DELETE /planets/1.json
  def destroy
    @planet.destroy
    respond_to do |format|
      format.html { redirect_to planets_url, notice: 'Planet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planet
      @planet = Planet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planet_params
      params.require(:planet).permit(:name, :distance_from_earth, :nearest_star)
    end
end

21-rails-review/app/controllers/scientists_controller.rb
class ScientistsController < ApplicationController
  def index
    @scientists = Scientist.all
    @yay = "Science is cool!"
    # render :index
  end

  def show
    @scientist = Scientist.find(params[:id])
  end

  def new
    @scientist = Scientist.new
    render :new
  end

  def create
    @scientist = Scientist.new(run_strong_params_for_scientist)
    if @scientist.save
      redirect_to scientist_path(@scientist) # show page
    else 
      render :new 
    end
  end

  def edit
    @scientist = Scientist.find(params[:id])
    render :edit
  end

  def update
    @scientist = Scientist.find(params[:id])
    @scientist.update(run_strong_params_for_scientist)
    if @scientist.valid?
      redirect_to scientist_path(@scientist)
    else 
      render :edit 
    end

  end

  def destroy
    Scientist.destroy(params[:id])
    redirect_to scientists_path
  end

  private 

  def run_strong_params_for_scientist
    params.require(:scientist).permit(:name, :field_of_study)
  end

end

21-rails-review/app/helpers/missions_helper.rb
module MissionsHelper
end

21-rails-review/app/helpers/planets_helper.rb
module PlanetsHelper
end

21-rails-review/app/helpers/scientists_helper.rb
module ScientistsHelper
end

21-rails-review/app/views/application/about.html.erb
<h1>About my app</h1>

<div>Total number of scientists: <%= @num_scientists %></div>
<div>Total number of planets: <%= @num_planets %> </div>

21-rails-review/app/views/missions/new.html.erb
<h1>Missions#new</h1>
<p>Find me in app/views/missions/new.html.erb</p>

<%= form_for @mission do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :scientist %>
    <%= collection_select :mission, :scientist_id, Scientist.abc_order, :id, :name %>
    <%= f.label :planet %>

    <%= f.submit %>
<% end %>

21-rails-review/app/views/planets/_form.html.erb
<%= form_with(model: planet, local: true) do |form| %>
  <% if planet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(planet.errors.count, "error") %> prohibited this planet from being saved:</h2>

      <ul>
        <% planet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :distance_from_earth %>
    <%= form.text_field :distance_from_earth %>
  </div>

  <div class="field">
    <%= form.label :nearest_star %>
    <%= form.text_field :nearest_star %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

21-rails-review/app/views/planets/edit.html.erb
<h1>Editing Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Show', @planet %> |
<%= link_to 'Back', planets_path %>

21-rails-review/app/views/planets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Planets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Light years from earth</th>
      <th>Nearest star</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @planets.each do |planet| %>
      <tr>
        <td><%= planet.name %></td>
        <td><%= planet.distance_from_earth %></td>
        <td><%= planet.nearest_star %></td>
        <td><%= link_to 'Show', planet %></td>
        <td><%= link_to 'Edit', edit_planet_path(planet) %></td>
        <td><%= link_to 'Destroy', planet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Planet', new_planet_path %>

21-rails-review/app/views/planets/new.html.erb
<h1>New Planet</h1>

<%= render 'form', planet: @planet %>

<%= link_to 'Back', planets_path %>

21-rails-review/app/views/planets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @planet.name %>
</p>

<p>
  <strong>Light years from earth:</strong>
  <%= @planet.distance_from_earth %>
</p>

<p>
  <strong>Nearest star:</strong>
  <%= @planet.nearest_star %>
</p>

<%= link_to 'Edit', edit_planet_path(@planet) %> |
<%= link_to 'Back', planets_path %>

21-rails-review/app/views/scientists/_scientist_form.html.erb
<% if @scientist.errors %>
    <% @scientist.errors.full_messages.each do |message| %>
        <div><%= message %></div>
    <% end %>
<% end %>
<%= form_for @scientist do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :field_of_study %>
    <%= f.text_field :field_of_study %>
    <%= f.submit %>
<% end %>

21-rails-review/app/views/scientists/edit.html.erb
<h1>Edit this scientist</h1>
<%= render partial: "scientist_form" %>

21-rails-review/app/views/scientists/index.html.erb
<h1>Scientists#index</h1>
<p>Find me in app/views/scientists/index.html.erb</p>
<%= @yay %>
<% @scientists.each do |sci| %>
    <div><%= link_to sci.name, scientist_path(sci) %></div>
<% end %>

21-rails-review/app/views/scientists/new.html.erb
<h1>Create a new scientist</h1>

<%= render partial: "scientist_form" %>

21-rails-review/app/views/scientists/show.html.erb
<h1><%= @scientist.name %></h1>
<h2>Specialty: <%= @scientist.field_of_study %></h2>


<% @scientist.planets.each do |planet| %>
    <div><%= link_to planet.name, planet_path(planet)%></div>
<% end %>


<%= button_to "Delete this scientist", scientist_path(@scientist), :method => :delete %>

<%= link_to "Delete this scientist with a get", delete_scientist_path(@scientist)%>