26-css-frameworks/config/routes.rb
Rails.application.routes.draw do
  resources :trees, only: [:index, :show, :new, :create]
  resources :users, only: [:index, :show, :edit, :update]
  get "/", to: "application#home", as: "home"
end

26-css-frameworks/app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :tree
    belongs_to :user
end

26-css-frameworks/app/models/tree.rb
class Tree < ApplicationRecord
    has_many :favorites
    has_many :users, through: :favorites

    validates_presence_of :common_name, :binomial_name, :category
    validates :common_name, uniqueness: true
    validates :binomial_name, uniqueness: true
    validates :category, :inclusion => %w(deciduous coniferous)
    validate :two_words

    private

    def two_words
        if self.binomial_name.split.length != 2
            self.errors.add(:binomial_name, "Must be two words long")
        end
    end
end

26-css-frameworks/app/models/user.rb
class User < ApplicationRecord
    has_many :favorites
    has_many :trees, through: :favorites

    validates_presence_of :name, :username
    validates :username, uniqueness: true
end

26-css-frameworks/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def home
    end
end

26-css-frameworks/app/controllers/trees_controller.rb
class TreesController < ApplicationController
    def index 
        @all_trees = Tree.all
    end

    def show
        @tree = Tree.find(params[:id])
    end

    def new
        @tree = Tree.new
    end
    
    def create 
        @tree = Tree.create(tree_params)
        if @tree.errors.any?
            render :new
        else
            redirect_to @tree
        end
    end

    private

    def tree_params
        params.require(:tree).permit(:common_name, :binomial_name, :category, :user_ids, :image)
    end
end

26-css-frameworks/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index 
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        @user.update(user_params)
        if @user.errors.any?
            render :edit
        else
            redirect_to @user
        end
    end

    private
    
    def user_params
        params.require(:user).permit(:name, :username, :image, tree_ids: [])
    end
end

26-css-frameworks/app/helpers/trees_helper.rb
module TreesHelper
end

26-css-frameworks/app/helpers/users_helper.rb
module UsersHelper
end

26-css-frameworks/app/views/application/home.html.erb
<div id="home-heading" class="heading primary-header" id="special-home-header">Tree Tracker</div>
<div class="intro wrapper">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    <br><br>
    <%= link_to "Add a new tree", new_tree_path, class: "ui yellow button", id: "home-button"  %>
</div>