27-testing-in-rails/config/routes.rb
Rails.application.routes.draw do
  resources :flags, only: [:index, :show, :new, :create]
  resources :users, only: [:new, :create]
  
  get 'best_flag', to: "flags#best_flag", as: "best_flag"

  get '/login', to: "sessions#login"
  post "/login", to: "sessions#process_login"
  delete "/logout", to: "sessions#logout"
end

27-testing-in-rails/app/models/flag.rb
class Flag < ApplicationRecord
end

27-testing-in-rails/app/models/user.rb
class User < ApplicationRecord
    has_secure_password
end

27-testing-in-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :logged_in?, :current_user

    def logged_in?
        !!session[:user_id]
    end

    def current_user
        if logged_in?
            return User.find(session[:user_id])
        else
            return nil
        end
    end

    def authorized
        redirect_to login_path unless logged_in?
    end
end

27-testing-in-rails/app/controllers/flags_controller.rb
class FlagsController < ApplicationController
  before_action :authorized, except: [:index, :show, :best_flag]

  def index
    @flags = Flag.all
  end

  def show
    @flag = Flag.find(params[:id])
  end

  def best_flag
    @flag = Flag.find_by(rating: 5)
    render :best_flag_view
  end

  def new
    @flag = Flag.new
    @ratings = [1, 2, 3, 4, 5]
    @flag_types = ["National", "State/Territory", "Regional", "Municipal", "Historical", "Humorous"]
  end

  def create
    flag = Flag.create(flag_params)
    redirect_to flag_path(flag)
  end

  private

  def flag_params
    params.require(:flag).permit(:region, :current, :info, :flag_type, :image_url, :rating)
  end

end

27-testing-in-rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def login
    end
  
    def process_login
      @user = User.find_by(username: params[:username])
      if @user && @user.authenticate(params[:password])
        session[:user_id] = @user.id 
        redirect_to flags_path 
      else
        flash.now[:login_error] = "No user found with those credentials"
        render :login
      end
    end
  
    def logout
      session.clear
      redirect_to login_path
    end
  end

27-testing-in-rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
      if @user.valid?
        @user.save
        session[:user_id] = @user.id
        redirect_to flags_path
      else
        render :new
      end
    end
  
    private
  
    def user_params
      params.require(:user).permit(:username, :password)
    end
  end

27-testing-in-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

27-testing-in-rails/app/helpers/flags_helper.rb
module FlagsHelper
end

27-testing-in-rails/app/views/flags/best_flag_view.html.erb
<div class="heading secondary-header">Here it is — the best flag.</div>
<div class="wrapper center main-wrapper">
<%= image_tag @flag.image_url, class: "best-image" %>
</div>
<div class="center wrapper">
    <%=link_to "See inferior flags", flags_path, class: "ui button"%>
</div>

27-testing-in-rails/app/views/flags/index.html.erb
<div class="heading primary-header">
    FLAGS FLAGS FLAGS
    <div class="ui secondary menu", id="main-menu">
        <%= link_to "SEE THE BEST ONE", best_flag_path, class: "item", id: "main-menu-item" %>
        <%= link_to "ADD A NEW FLAG", new_flag_path, class: "item", id: "main-menu-item" %>
        <% if logged_in? %>
            <%= link_to "LOG OUT", logout_path, method: :delete, class: "item", id: "main-menu-item" %>
        <% else %>
            <%= link_to "LOG IN", login_path, class: "item", id: "main-menu-item" %>
        <% end %>
    </div>
</div>

<div class="gallery">
<% @flags.each do |flag| %>
    <%= link_to flag.region, flag_path(flag), class: "ui button", id: "region-btn" %>
    <%= image_tag flag.image_url, class: "gallery-image" %>
<% end %>
</div>

27-testing-in-rails/app/views/flags/new.html.erb
<div class="heading secondary-header">Add a new flag</div>

<div class="flag-form">
    <%= form_for @flag, html: {class: "ui form"} do |f| %>
        <h4 class="ui dividing header">You are logged in as <span class="username"><%= current_user.username %></span></h4>
        <div class="field">
            <%= f.label :region %>
            <%= f.text_field :region %>
        </div>
        <div class="field">    
            <label>Interesting fact</label>
            <%= f.text_field :info %><br>
        </div>
        <div class="field">
            <label>Flag image (url)</label>
            <%= f.text_field :image_url %>
        </div>
        <div class="two fields">
            <div class="field">
                <%= f.label :flag_type %>
                <%= f.select :flag_type, @flag_types %>
            </div>
            <div class="field">  
                <%= f.label :rating %>
                <%= f.select :rating, @ratings, prompt: "Select" %>
            </div>
        </div>
        <div class="field">
            <label>Is this a current flag?</label>
            <div class="radio-field">
                <div class="inline fields">
                    <%= f.radio_button :current, true, class: "ui radio checkbox", checked: true %> 
                    <%= label :current?, 'Yes' %>
                    <%= f.radio_button :current, false, class: "ui radio checkbox" %>
                    <%= label :current?, 'No' %>
                </div>
            </div>
        </div>
        <%= f.submit "Add flag", class: "ui button"%>
    <% end %>
</div>

27-testing-in-rails/app/views/flags/show.html.erb
<div class="heading secondary-header">Flag of <%= @flag.region %></div>
<div class="ui container">
<div class="main-wrapper wrapper">
    <div class="center">
        <p class="flag-info"><%= @flag.info %></p>
        <%= image_tag @flag.image_url, class: "show-image" %>
    </div>
    <div class="ui list">
        <div class="item">
            <i class="clock icon"></i>
            <div class="content">
                <%= @flag.current? ? "This is the current flag of #{@flag.region}" : "This is NOT the current flag of #{@flag.region}"%>
            </div>
        </div>
        <div class="item">
            <i class="question circle icon"></i>
            <div class="content">
                Type: <%= @flag.flag_type %>
            </div>
        </div>
    </div>
</div>
<div class="center wrapper">
    <%=link_to "See all flags", flags_path, class: "ui button"%>
</div>
</div>

27-testing-in-rails/app/views/users/new.html.erb
<%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit  %>
<% end %>